### ISSUE TITLE
Couldn't find declaration files in Typescript

### ISSUE THREAD

**Issue by philippedasilva-orizone** [mat-sz/vue-letter#1]
Hi @mat-sz,

I'm giving a try to your vue component and once installed, when simply trying to add it to my project, I get the following error from Vetur and VueDX plugins in vs code:
`Could not find a declaration file for module 'vue-letter'. '/Volumes/Projects/Orizone.io/origami.web/node_modules/vue-letter/dist/Letter.umd.js' implicitly has an 'any' type.
 Try 'npm i --save-dev @types/vue-letter' if it exists or add a new declaration (.d.ts) file containing 'declare module 'vue-letter';`

On the browser, I get the following at runtime:
```SyntaxError: The requested module '/node_modules/vue/dist/vue.runtime.esm-bundler.js' does not provide an export named 'default'```

I'm using Vue 3.0.5 with vue-letter 0.1.2 on top of a vitejs project.

Thanks

**Comment by mat-sz** [comment]
Hi @philippedasilva-orizone,

Vue 3.x is still in a preview state. I will release an updated version of the package once Vue 3.x becomes stable.

**Comment by mat-sz** [comment]
Hey @philippedasilva-orizone

Apologies for the *slight* delay (2 years...) but it should work now, could you give it a try?

**Comment by mat-sz** [comment]
Closing this, reopen if still a problem.
